// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBilcqFy-LhnLaydLcoDqxjSS8dR8O3xSg',
    appId: '1:637512075578:web:67e1c720490fd86a21e803',
    messagingSenderId: '637512075578',
    projectId: 'child-nutrition-tracker',
    authDomain: 'child-nutrition-tracker.firebaseapp.com',
    storageBucket: 'child-nutrition-tracker.firebasestorage.app',
    measurementId: 'G-BGVCNWG0BT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2yRUpbF1kW_ggmb_Sls2G05BDE8Eqyu4',
    appId: '1:637512075578:android:8f0d96a94f8e61ac21e803',
    messagingSenderId: '637512075578',
    projectId: 'child-nutrition-tracker',
    storageBucket: 'child-nutrition-tracker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCQEJe8wrnnPwS0ifoprJGaZkLnpBQvwU',
    appId: '1:637512075578:ios:4a3d27d81d52d2ff21e803',
    messagingSenderId: '637512075578',
    projectId: 'child-nutrition-tracker',
    storageBucket: 'child-nutrition-tracker.firebasestorage.app',
    iosBundleId: 'com.example.childNutritionTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCQEJe8wrnnPwS0ifoprJGaZkLnpBQvwU',
    appId: '1:637512075578:ios:4a3d27d81d52d2ff21e803',
    messagingSenderId: '637512075578',
    projectId: 'child-nutrition-tracker',
    storageBucket: 'child-nutrition-tracker.firebasestorage.app',
    iosBundleId: 'com.example.childNutritionTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBilcqFy-LhnLaydLcoDqxjSS8dR8O3xSg',
    appId: '1:637512075578:web:a261bcd4f567d9d521e803',
    messagingSenderId: '637512075578',
    projectId: 'child-nutrition-tracker',
    authDomain: 'child-nutrition-tracker.firebaseapp.com',
    storageBucket: 'child-nutrition-tracker.firebasestorage.app',
    measurementId: 'G-32KSYWM2HM',
  );
}
